# Generated by Django 3.1.7 on 2021-03-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20210326_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='home', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default='2000-09-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
