# Generated by Django 3.1.7 on 2021-03-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
