# Generated by Django 3.1.7 on 2021-03-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_auto_20210326_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
