# Generated by Django 3.1.7 on 2021-03-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0019_auto_20210327_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productincart',
            options={'verbose_name_plural': 'ProductsInCarts'},
        ),
        migrations.AddField(
            model_name='address',
            name='nickname',
            field=models.CharField(default='home', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=125),
        ),
    ]
