# Generated by Django 3.1.7 on 2021-03-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.address'),
        ),
    ]
