# Generated by Django 3.1.7 on 2021-03-27 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0022_shoppingcart_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='nickname',
        ),
    ]
