# Generated by Django 3.1.7 on 2021-03-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0023_remove_address_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
