# Generated by Django 3.1.7 on 2021-03-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0026_auto_20210327_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
