# Generated by Django 3.1.7 on 2021-03-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0027_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='paintings'),
            preserve_default=False,
        ),
    ]
