# Generated by Django 3.1.7 on 2021-03-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0028_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unique',
        ),
    ]
